a=int(input("Enter the age1:"))
b=int(input("Enter the age2:"))
c=int(input("Enter the age3:"))
oldest=max(a,b,c)
youngest=min(a,b,c)
print(f"the oldest is: {oldest}")
print(f"the youngest is: {youngest}")